### ISSUE TITLE
IE 11 never finishes loading

### ISSUE THREAD

**Issue by zatziky** [yyh1102/vue-lazyload-images#3]
In Chrome the image is loaded. In IE 11 it never finishes loading and only the spinner is displayed:

![image](https://user-images.githubusercontent.com/2794365/31053913-60a7ef94-a6a7-11e7-981a-3e1a01c83fab.png)

The Network tab in developer tools doesn't show a request to download image would start either. I tried to debug it but IE 11 is not very friendly. Do you know why is this happening? @yyh1102

**Comment by lowesyang** [comment]
Fixed. Please install the latest version.

**Comment by zatziky** [comment]
Thank you!
